# GitHub Sponsors and Custom Donation Links

github: [mleem97]
ko_fi: mleem
custom:
  [
    "https://www.buymeacoffee.com/marvinleedj",
    "https://paypal.me/mleem97",
    "https://revolut.me/animusfound",
  ]
